### ISSUE TITLE
[Feature] autocollapse  

### ISSUE THREAD

**Issue by loadiiing42** [krzmig/strelloids#17]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I'd like to have a autocollapse  function if there isn't card

**Describe alternatives you've considered**

**Additional context**

**Comment by krzmig** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[GitHub][Feature] Auto collapse empty lists](https://trello.com/c/vzCzMjbk/194-githubfeature-auto-collapse-empty-lists)

**Comment by krzmig** [comment]
Added in version: 2020.9.26
