### ISSUE TITLE
Outside card shows empty space instead of label

### ISSUE THREAD

**Issue by Cassidy13K** [krzmig/strelloids#2]
- Browser: Firefox Quantum
- version of strelloids: latest
- issue started appearing: a few days ago 
- issue gets immediately fixed by disabling extension and comes back when enabling extension
- enabled extension settings: "Show list card counter", "enable cards separator"

reproduce:

- have a card
- add a label
--> label shows inside card (correct)
- close card
--> label is not visible outside card, only shows empty space

![32s_31m_22h_date_10_06_2019](https://user-images.githubusercontent.com/26398668/59224802-86594800-8bcf-11e9-9135-a47616038b62.png)

Thank you for looking into it and thanks for providing the extension for free. :)

**Comment by krzmig** [comment]
Hello,
bug fixed, new version on the market.
Thanks for issue and using :)

Ps: Tip for today, you can click on the standard trello label to toggle text showing on it.
