### ISSUE TITLE
[Bug] Auto Collapse Empty Lists not working

### ISSUE THREAD

**Issue by Cassidy13K** [krzmig/strelloids#20]
**Describe the bug**
The newest Strelloids Version added the Option "Auto collapse empty lists".
Enabling this option throws an error in the browser console.
It does not change the collapse status of any lists. 
Upon refreshing the page, the option is disabled again.

**To Reproduce**
1. Open the Strelloids Global settings
2. Select "Lists collapsing" category
3. open your browser console
4. enable or disable the check box
5. check your trello boards

**Expected behavior**
Expected all empty lists to be collapsed & the status of the option be saved upon page refresh.

**Screenshots**
![image](https://user-images.githubusercontent.com/26398668/94342258-385c9380-0010-11eb-9e84-5ae3dbdba0b5.png)

**Browser details**
 - OS: Windows 10
 - Browser: latest Firefox
 - Strelloids Version: 2020.9.26

**Additional context**
The error says something about quote exceeded. Perhaps the addon tries to collapse to many lists at once? It's unclear to me whether it will only collapse the ones on boards that are currently open in any browser tab, or if all the user is a member of. 
Especially if it's the last case the addon might be trying to collapse thousands of lists at the same time, since many users are part of big boards. Closing all open tabs with trello boards did not fix the issue.

**Comment by krzmig** [comment]
Hello,
I cannot reproduce your issue, but I found that Mozilla changed limitations for `storage.sync` (share addons data between all your connected browsers) starting from Firefox 79. Bug in console is unclear which limit has been exceeded. 

Can you run these command in developer console (from options page as in screenshot) and send result:

- ` getBrowserObject().storage.sync.getBytesInUse().then( console.log )` 
- ` getBrowserObject().storage.sync.get(null).then( (list) => { console.log( Object.keys(list).length ) })`

First will return size of your saved data and second one will return number of items saved on storage.

Thanks for report :)

**Comment by Cassidy13K** [comment]
Good afternoon,
Thank you for your swift reply and the new version. I did as instructed, please see the picture for the results you requested:
![image](https://user-images.githubusercontent.com/26398668/94344145-8e840380-001d-11eb-85c4-e8def3f37d9b.png)

For good measures, I have disabled all other addon except for Strelloids and ran the same commands, resulting in the exact same numbers.
Cheers :)

**Comment by krzmig** [comment]
Problem is both, amount of items and them size. I will try move lists settings from sync storage, to local, and keep global and boards settings in sync storage. I think that should fix your problem.

**Comment by krzmig** [comment]
Ok, I moved settings of list into local storage.

Can you download zip from below link and check is that will fix your problem?
https://github.com/krzmig/strelloids/releases/tag/v2020.9.27-beta

After download: 
- open new tab and enter `about:debugging`,
- click "This Firefox",
- click "Load Temporary Add-on" and select downloaded zip.

You can also run commands from the previous post and paste the results.

**Comment by Cassidy13K** [comment]
It seems to have worked. 👍 🎉 
The checkbox stays enabled upon refresh and lists get automatically collapsed. 
Please see the picture for the command results:

![image](https://user-images.githubusercontent.com/26398668/94366282-7375ca00-00d7-11eb-9ff5-be418fc9e3ec.png)

**Comment by krzmig** [comment]
Good to hear. I will upload new version to the market.
Many thanks for the report and help :)
