### ISSUE TITLE
[Bug] Extension not working after Trello update

### ISSUE THREAD

**Issue by rwjdk** [krzmig/strelloids#29]
Might be related to [Issue 20](https://github.com/krzmig/strelloids/issues/20), but it seems the collapse feature broke (since yesterday when it worked, so properly (chromium) browser change)

**To Reproduce**
Steps to reproduce the behavior (see screenshots):
1. Add Extension
2. Load board and notice collapse feature work
3. Refresh Page (F5)
4. The collapse feature does not appear (no collapse triangle)

**Expected behavior**
The collapse feature works all the time ;-)

**Screenshots**
First load or after Site Data Clear
![image](https://github.com/krzmig/strelloids/assets/7032102/8ff0e839-b918-4a98-92e8-71e2778143ae)

After refresh (F5)
![image](https://github.com/krzmig/strelloids/assets/7032102/d1204ae2-3033-47b2-b0e3-d85456d3bba2)

Site Data Clear settings to get it working again
![image](https://github.com/krzmig/strelloids/assets/7032102/082e4a03-15e4-409d-b20f-bf1c411324e5)

**Browser details**
 - OS: Windows 11 22H2
 - Browser: Tested on Edge (117.0.2045.47 (Official build) (64-bit)) + Vivadi (6.2.31.05.54)
 - Strelloids version 2020.9.27

**Comment by sirhand** [comment]
This just happened to me today. At the same time the scroll wheel started scrolling horizontally, so I had to disable "Overwrite vertical scroll on board with horizontal"

**Comment by rubcap** [comment]
@rwjdk @sirhand  Can confirm. Suddenly a lot of problems using Strelloids: collapsing, scrolling, prioritization (see https://github.com/krzmig/strelloids/issues/31) ... 

I've also deactivated "overwrite vertical scroll". 

Hope this can be fixed, because Strelloids is really useful.

**Comment by krzmig** [comment]
Trello is apparently changing its rendering engine, probably to react. The entire HTML structure on which the extension is based has been changed by this. It also does not update for everyone at the same time, I noticed yesterday that the extension is not working. The repair will unfortunately take some time....

**Comment by ristretto6** [comment]
Shoot, thanks for letting us know. If anyone finds a workaround or solution in the meantime, please let me know! The functionality that I'm most in need of at the moment is the ability to collapse/hide lists that are not in my current work focus. Thank you!

**Comment by rwjdk** [comment]
@krzmig : Thanks for the update. Hope it do not end up too too much work for you to have it working again (and if you need help with testing let us know) 🤞, and thanks for an awesome extension so far

**Comment by krzmig** [comment]
A new version for Firefox is now available.
Chrome as always does problems, after a long fight I was able to upload, but I do not know when they will accept it.
Because of chrome, separate branches must have been created `develop` for Firefox, and `develop-chrom` for Chrome. 
Later I will update the `master` and generate some release.
I hope it will be usable again o/

**Comment by rwjdk** [comment]
👍 Awesome work... Will test tomorrow

**Comment by rubcap** [comment]
OMG @krzmig, you're amazing! Thank you so much for such a quick fix❤️.
The problems (card prioritization, horizontal scroll, collapsing lists ...) seem to have disappeared (Firefox here).
 If I discover remaining issues, I'll report them.

**Comment by rwjdk** [comment]
~~Can confirm that everything is as Expected in Edge and Vivaldi with new version of Chrome Extension 🥳~~

I'm afraid I spoke too soon... All seemed well at first but there was the side-effect that cards could not be moved with drag&drop ;-( ... And After resetting application data things stopped working again (can't collapse columns :-/)

Update: Issue seems to be more with Vivaldi and Trello in general so ignore above... Works fine in Firefox

Update 2: If anyone else use Vivaldi, are here the reasons and solutions to the issue on that specific browser: https://community.atlassian.com/t5/Trello-questions/Label-text-being-selected-when-trying-to-drag-label/qaq-p/2507498
