### ISSUE TITLE
Strelloids dont work after atualization Chrome

### ISSUE THREAD

**Issue by ampel-editorial** [krzmig/strelloids#30]
Chrome updated and the Strelloids extension stopped working.

In Extensions, the error that appears is the following:
   "browser_specific_settings": {
       "gecko": {
          "id": "strelloids@krzmig.github.com",
          "strict_min_version": "57.0"
       }
    },

**Comment by krzmig** [comment]
The same as in #29

**Comment by ampel-editorial** [comment]
Tks

Monica Hamada
produtora editorial
(11) 9 9871-9141

________________________________
De: krzmig ***@***.***>
Enviado: sexta-feira, 20 de outubro de 2023 14:13
Para: krzmig/strelloids ***@***.***>
Cc: Ampel Produções Editoriais ***@***.***>; Author ***@***.***>
Assunto: Re: [krzmig/strelloids] Strelloids dont work after atualization Chrome (Issue #30)


The same as in #29<https://github.com/krzmig/strelloids/issues/29>
