### ISSUE TITLE
[Bug] Card priority not indicated any longer by colored line (card's left border)

### ISSUE THREAD

**Issue by rubcap** [krzmig/strelloids#31]
**Describe the bug**
Previously, when you set the priority by adding !1 in the card title or by using the drop-down in the card, the !1 was hidden in the card title and a colored line was added to the left border of the card (e.g. red for high priority). The colored line isn't shown any longer.

**To Reproduce**
1. Pick a card.
2. Add !1 to the title.
3. Close the card.
4. Check the card in the board view.

**Expected behavior**
The !1 in the title is hidden and a colored line is added to the left border of the card to indicate its priority.

**Screenshots**
(n/a)

**Browser details**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 118.0.2
 - Strelloids version: 2020.9.27.1

**Additional context**
-

**Comment by krzmig** [comment]
The same as in #29
