### ISSUE TITLE
Extension doesn't seem to work at all anymore...[Bug]

### ISSUE THREAD

**Issue by madebyernie** [krzmig/strelloids#32]
**Describe the bug**
For some reason, the extension doesn't seem to work at all anymore.  Its a shame as it was a key part of my process - I love it!!
Would massively appreciate if you could have a look although I know that's a big ask...
Thanks...

**To Reproduce**
The extension has been working flawlessly for me for a long time now on Chrome, Mac.
I guess perhaps there are conflicts with an update on Chrome?

**Expected behavior**
to be able to manipulate the cards/lists/boards of a Trello account.
The board layout seems to still work (default or multi-row lists)...

**Screenshots**
na

**Browser details**
 - Mac OS Monterey - 12.6.7
 - Chrome 
 - 117.0.5938.149
 - Latest Strelloids download from chrome store (2020.9.27)

**Additional context**
na

**Comment by ristretto6** [comment]
I'm having the same issue! Operating on Firefox and it just stopped working for me today. Was there an update that conflicted with this? I am no longer able to collapse my lists, or see card totals at the header of each list. I need these features back, I will go crazy if I can't hide the lists I'm not working on in the moment! Thanks.

**Comment by krzmig** [comment]
The same as in #29
