### ISSUE TITLE
Lists Overlapping [Bug]

### ISSUE THREAD

**Issue by Reddazrael** [krzmig/strelloids#8]
**Describe the bug**
When collapsing a list, lists now overlap with each other. I assume this is due to Trello's new "create card from template" function.

**To Reproduce**
1. Collapse List in a multi-list board.
2. There you go, problem.

**Expected behavior**
Lists are neatly lines up next to each other, not overlapping.

**Screenshots**
![Example](https://user-images.githubusercontent.com/33796139/67430500-5627aa00-f5b0-11e9-8ac7-6f8d262cfde4.png)

**Browser details**
 - OS: Windows 7 x64
 - Operta
 - 63.0.3368.107
 - 5.17.5

**Additional context**
Did not occur before Trello updated with a "create from template" icon, so I'm assuming that's the cause of the issue.

**Comment by Reddazrael** [comment]
...Well, this is strange. I refreshing the page with an errant keystroke and the bug appears to no longer be occurring. The list collapses just fine now, without the icon causing overlap, despite a refesh not having fixed the issue previously. Huh. If the bug cannot be reproduced at this point, I suppose this can be closed without further comment. My apologies.

**Comment by AtzeFisch** [comment]
This was fixed earlier today :)

**Comment by krzmig** [comment]
I'm so fast! :D

Thank for report and replay :)
