### ISSUE TITLE
[Feature] Option to collapse or expand all lists on a board

### ISSUE THREAD

**Issue by Cassidy13K** [krzmig/strelloids#9]
**Is your feature request related to a problem? Please describe.**
When working on boards that contains many lists of which you currently only need one, you need to manually collapse every single unwanted list to get rid of the clutter.

**Describe the solution you'd like**
Add an option which allows to collapse all lists on a board. This option could e.g. be a button or a checkbox in the menu when you click on the extension in your browser.
Hence also an option that allows to expand all lists on a board (opposite of the above).
*Note* Please make this option be board-specific. So tapping it should not collapse/expand all lists on all boards, only the board you are currently viewing.

**Describe alternatives you've considered**
Can't think of an alternative, but made a related feature request, see 

**Additional context**
According to another issue #3 you are using specific list IDs to collapse them. Trello API afaik has a callback to get all list IDs on a board, so this feature might be quick to implement.

Thank you for this great addon. :-)

**Comment by krzmig** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[GitHub][Feature] Collapse/expand all lists](https://trello.com/c/Bw08ASTM/196-githubfeature-collapse-expand-all-lists)

**Comment by krzmig** [comment]
Added in version: 2020.9.26
